# Generated by Django 5.2.6 on 2025-09-23 21:02

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название букета')),
                ('image', models.ImageField(blank=True, upload_to='bouquets/', verbose_name='Изображение букета')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('composition', models.TextField(blank=True, verbose_name='Состав')),
                ('occasion', models.CharField(choices=[('День рождения', 'День рождения'), ('Свадьба', 'Свадьба'), ('В школу', 'В школу'), ('Без повода', 'Без повода'), ('Другой повод', 'Другой повод')], default='Без повода', max_length=50, verbose_name='Повод')),
                ('color_scheme', models.CharField(choices=[('Без цветовой гаммы', 'Без цветовой гаммы'), ('Красные', 'Красные'), ('Синие', 'Синие')], default='Без цветовой гаммы', max_length=50, verbose_name='Цветовая гамма')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('florist_notified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заявка на консультацию',
                'verbose_name_plural': 'Заявки на консультацию',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('home_address', models.CharField(blank=True, max_length=256, verbose_name='Адрес доставки')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.PositiveIntegerField(default=0, verbose_name='Цена заказа')),
                ('order_status', models.CharField(choices=[('Заявка обрабатывается', 'Заявка обрабатывается'), ('Собираем ваш букет', 'Собираем ваш букет'), ('Букет в пути', 'Букет в пути'), ('Букет у вас', 'Букет у вас')], default='Заявка обрабатывается', max_length=50, verbose_name='Статус заказа')),
                ('delivery_address', models.CharField(max_length=256, verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('delivery_time', models.CharField(max_length=30, verbose_name='Время доставки')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.bouquet', verbose_name='Букет')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
