# Generated by Django 5.2.6 on 2025-09-24 18:54

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя курьера')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='color_scheme',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='florist_notified',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='budget',
            field=models.CharField(choices=[('до 1000', 'до 1000'), ('1000-5000', '1000-5000'), ('от 5000', 'от 5000')], default='1000-5000', max_length=50, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='occasion',
            field=models.CharField(choices=[('Свадьба', 'Свадьба'), ('День рождения', 'День рождения'), ('Без повода', 'Без повода'), ('Другой повод', 'Другой повод')], default='Без повода', max_length=50, verbose_name='Повод'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.courier', verbose_name='Курьер'),
        ),
    ]
