# Generated by Django 5.2.6 on 2025-09-25 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_courier_remove_bouquet_color_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='height',
            field=models.PositiveIntegerField(default=50, verbose_name='Высота (см)'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='width',
            field=models.PositiveIntegerField(default=30, verbose_name='Ширина (см)'),
        ),
        migrations.AddField(
            model_name='courier',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Для уведомлений о заказах', max_length=50, verbose_name='Telegram Chat ID'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=36, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.order')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
