# Generated by Django 5.2.6 on 2025-09-26 08:40

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bouquet_height_bouquet_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Florist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя флориста')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Для уведомлений о заявках', max_length=50, verbose_name='Telegram Chat ID')),
            ],
            options={
                'verbose_name': 'Флорист',
                'verbose_name_plural': 'Флористы',
            },
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='height',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='width',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=36, unique=True, verbose_name='ID платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='pending', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='florist',
            field=models.ForeignKey(blank=True, help_text='Флорист, которому назначена заявка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.florist', verbose_name='Флорист'),
        ),
    ]
